### PR TITLE
Wip master

### PR DESCRIPTION
**Pull request by azat-co**
CC @AnnJohn @vicfriedman

### CODE REVIEW

**Comment by victhevenot** [comment]
@azat-co this is really great! only thing is when i tried to run `node server`, the terminal just hung. i never saw anything printed in the console.

**Comment by azat-co** [comment]
@vicfriedman you need to open your browser as per instructions. 
You can run it with `node server`, then open your browser at http://localhost:3000/users and notice the output in the browser:

I actually get the a lot when people just stare at their terminal expecting something without making requests... so I added more instructions.

**Comment by victhevenot** [comment]
much better! - this server can only handle `GET` requests right now, correct? or can it also handle POST/PUTS/DELETE requests? maybe add in a paragraph about that

**Comment by azat-co** [comment]
@vicfriedman good point, done, done and done! yay :santa:

**Pull request merged**
